apiVersion: v1
kind: Service
metadata:
  name: simple-http-server-service
  labels:
    app: simple-http-server
spec:
  selector:
    app: simple-http-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
